version: 0.2

phases: 
  pre_build:
    commands:
      - echo Deployment started on `date`
      - echo Syncing S3 Content
      - aws s3 sync ./public/ s3://notesapp-serverless
  build:
    commands:
      - echo Invalidating CloudFront Cache
      # - aws cloudfront create-invalidation --distribution-id E1VJT5X5RHYOWL --paths "/*"
  post_build:
    commands:
      - echo Deployment completed on `date`